[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
once_cell = "1.19.0"
wit-bindgen = {version = "0.39.0"}
wit-bindgen-rt = {version = "0.39.0", features = ["async"]}

[lib]
crate-type = ["cdylib"]
