[package]
name = "huygens_service"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
cargo-features = "0.0.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
wasm-runner = {path = "../wasm_runner"}
